config/routes.rb
OnlineRetailer::Application.routes.draw do
  resources :products
  resources :reviews, :only => [:create]


  root :to => 'products#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :available, :description, :image, :name, :price#, :photo
  has_many :reviews
  #has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/default.jpg"
  #validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  #validates :price,numericality: {greater_than_or_equal_to: 0.01}
  #validates :available,:description,:image,:name,:price ,presence: true
   def self.search(search)
   if search
     find(:all,conditions => ['name like ?',"%#{search}%"])
   else
     find(:all)
   end
   end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  attr_accessible :content, :customer_name, :product_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @top_products = Product.limit(7)
    if params[:search]
      @products = Product.where("name like ?", "%#{params[:search]}%").page(params[:page]).per_page(5)
    else
      @products = Product.page(params[:page]).per_page(5)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @reviews =  @product.reviews

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    params[:product][:available] = params[:product][:available].to_s == "In Stock" ? true : false;
    logger.info "------------------------------------------#{params.inspect}"
    #raise "error"
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    logger.info "====================#{params.inspect}"
    params[:product][:available] = params[:product][:available].to_s == "In Stock" ? true : false;

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   def create
   Review.create(customer_name: params[:customer_name] , content: params[:content] , product_id: params[:product_id] );
   redirect_to product_path(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineRetailer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" style="margin-bottom: 60px;">
	<div class="row">
		<div class="span12">
			<h1 >ONLINE RETAILER</h1>
			<hr>
			<%= yield %>
		</div>
	</div>
</div>

</body>
</html>

app/views/products/_form.html.erb
 <%= form_for @product, :html => {:id => "product", :multipart => true} do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name%>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description ,rows: 5 %>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %>
    </div>
    <!-- <div class="field"> -->
    <%#= f.label :image %><!-- <br /> -->
    <%#= f.file_field :photo %>
    <!-- </div> -->
    <div class="field">
      <%= f.radio_button :available,'In Stock' %>
      <%= f.label :available,'in stock' %><br />

      <%= f.radio_button :available,'Out of Stock'%>
      <%= f.label :available,'out of stock' %><br />

    </div>
    <div class="actions">
      <%= f.submit 'Save', :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="clearfix">
  <h1>Top Products</h1>
  <ul style = "border: 1px solid; padding: 5px;">
  <% @top_products.each do |product| %>
    <li style="margin-right: 10px; width: 110px; list-style: none; display: inline-block;">
    <%#= image_tag product.photo.url(:thumb), :style => "display:block; height:100px; width: 100px;" %>
    <img src="/assets/default.jpg" style="display:block; height:100px; width: 100px;">
    <%= link_to product.name, product_path(product)%>
    </li>
  <% end %>
</ul>
</div>
<div class="clearfix">
<h1 class="pull-left">Products</h1>
<%= form_tag products_path, :method => 'get', class: "pull-right" do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
</div>
<hr>
<div>
  <% @products.each do |product| %>
    <div style="border-bottom: 1px solid black; padding:10px;" class="clearfix">
      <div style="float:left; margin-right: 10px;">
      <%#= image_tag product.photo.url(:thumb) %>
      <img src="/assets/default.jpg" style="display:block; height:100px; width: 100px;">
      </div>
      <div>
        <%= link_to product.name, product_path(product)%>
        <div>$<%= product.price%></div>
        <div><%= product.description.to_s.truncate(200) %></div>
      </div>
    </div>
  <% end %>
</div>

<br />
<div class="pull-right">
<%= link_to 'New Product', new_product_path %> <br>
<%= will_paginate @products %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Cancel', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="border-bottom: 2px solid #000; padding-bottom: 10px;">
  <div class="span12"><%= @product.name %></div>
  <div class="span12">
    <div class="row">
    <div class="span3">
      <%#= image_tag @product.photo.url, :style => "display:block;" %>
      <img src="/assets/default.jpg" style="display:block;">
      Price: $<%= @product.price %></br>
      Availability: <%= @product.available ? "In Stock" : "Out of Stock" %> 
    </div>
    <div class="span9">
      <%= @product.description %>
    </div>      
    </div>
  </div>
</div>
<div class="pull-right">
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back to list', products_path %>
</div>

<div class="row">
<h1>Reviews</h1>
<hr>
<% @reviews.each do |review|%>
<div style="border-bottom: 1px solid black; margin:10px;">
<strong><%= review.customer_name + ": "%></strong><%= review.content %>
</div>
<% end %>
</div>
<div class="pull-right">
<h2>Add Review</h2>
<%= form_tag("/reviews", method: "post", id: "reviews") do  %>
    <div class="field">
      <%= label_tag :Name %><br/>
      <%= text_field_tag(:customer_name) %>
    </div>
    <div class="field">
       <%= label_tag :content %><br/>
      <%= text_area_tag(:content) %>
    </div>
    <%= hidden_field_tag 'product_id', @product.id %>
    <div class="actions">
      <%= submit_tag("Submit", :class => "btn, btn-success") %>
    </div>
<% end %>
</div>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
    <p>
      <b> review</b>
      <%= review.customer_name %>
      <b>content</b>
      <%= review.content %>
    </p>
<% end %>
<%= link_to "Add Review",new_review_path%>

app/views/reviews/new.html.erb
<h2>add review</h2>
<%= form_for ([@review]) do |f| %>
    <div class="field">
      <%= f.label :customer_name %><br/>
      <%= f.text_field :customer_name %>
    </div>
    <div class="field">
      <%= f.label :content %><br/>
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/reviews/show.html.erb
<p>
  <b>name: </b>
  <%= @review.customer_name %>
  <b>content:</b>
  <%= @review.content %>
</p>
<%= link_to "back"%>